import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Classic Sea Salt Chips",
    brand: "Crunch Co",
    category: "chips",
    price: 4.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    description: "Perfectly crispy kettle-cooked chips with a light touch of sea salt. Made from premium potatoes and cooked in small batches for the perfect crunch.",
    tags: ["gluten-free", "vegan", "bestseller"],
    nutrition: {
      calories: 150,
      protein: "2g",
      carbs: "15g",
      fat: "10g",
    },
    variants: [
      { id: "single", name: "Single Pack", price: 4.99 },
      { id: "family", name: "Family Size", price: 12.99 },
    ],
    inStock: true,
  },
  {
    id: "2",
    name: "Spicy Jalapeño Poppers",
    brand: "Heat Street",
    category: "chips",
    price: 5.49,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg"],
    description: "Bold and spicy chips with real jalapeño flavor. Perfect for heat lovers looking for an authentic kick.",
    tags: ["spicy", "gluten-free", "new"],
    nutrition: {
      calories: 160,
      protein: "2g",
      carbs: "16g",
      fat: "11g",
    },
    inStock: true,
  },
  {
    id: "3",
    name: "Dark Chocolate Almonds",
    brand: "Sweet Spot",
    category: "chocolate",
    price: 6.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg"],
    description: "Premium whole almonds covered in rich 70% dark chocolate. A perfect balance of sweet and nutty.",
    tags: ["organic", "protein", "bestseller"],
    nutrition: {
      calories: 210,
      protein: "5g",
      carbs: "18g",
      fat: "15g",
    },
    inStock: true,
  },
  {
    id: "4",
    name: "Mixed Berry Trail Mix",
    brand: "Nature's Path",
    category: "trail-mix",
    price: 7.99,
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg"],
    description: "A wholesome blend of dried berries, nuts, and seeds. Perfect for hiking or as a healthy snack.",
    tags: ["organic", "vegan", "protein"],
    nutrition: {
      calories: 180,
      protein: "6g",
      carbs: "20g",
      fat: "9g",
    },
    inStock: true,
  },
  {
    id: "5",
    name: "Honey BBQ Beef Jerky",
    brand: "Wild West",
    category: "jerky",
    price: 9.99,
    image: "/placeholder.svg",
    description: "Premium grass-fed beef jerky with a sweet and smoky BBQ glaze. High in protein, low in fat.",
    tags: ["high-protein", "gluten-free"],
    nutrition: {
      calories: 80,
      protein: "12g",
      carbs: "6g",
      fat: "2g",
    },
    inStock: true,
  },
  {
    id: "6",
    name: "Cheddar Cheese Puffs",
    brand: "Crunch Co",
    category: "chips",
    price: 3.99,
    image: "/placeholder.svg",
    description: "Light and airy cheese puffs with real cheddar flavor. A nostalgic favorite for all ages.",
    tags: ["bestseller"],
    nutrition: {
      calories: 140,
      protein: "2g",
      carbs: "14g",
      fat: "9g",
    },
    inStock: true,
  },
  {
    id: "7",
    name: "Matcha Energy Bites",
    brand: "Zen Snacks",
    category: "energy",
    price: 8.49,
    image: "/placeholder.svg",
    description: "Organic matcha green tea energy bites with dates and coconut. Natural energy boost without the crash.",
    tags: ["organic", "vegan", "new"],
    nutrition: {
      calories: 120,
      protein: "3g",
      carbs: "18g",
      fat: "5g",
    },
    inStock: true,
  },
  {
    id: "8",
    name: "Salted Caramel Popcorn",
    brand: "Pop Culture",
    category: "popcorn",
    price: 5.99,
    image: "/placeholder.svg",
    description: "Gourmet popcorn drizzled with salted caramel. The perfect sweet and salty combination.",
    tags: ["gluten-free", "bestseller"],
    nutrition: {
      calories: 170,
      protein: "2g",
      carbs: "22g",
      fat: "8g",
    },
    inStock: false,
  },
];

export const brands = ["Crunch Co", "Heat Street", "Sweet Spot", "Nature's Path", "Wild West", "Zen Snacks", "Pop Culture"];

export const categories = [
  { id: "all", name: "All Snacks" },
  { id: "chips", name: "Chips" },
  { id: "chocolate", name: "Chocolate" },
  { id: "trail-mix", name: "Trail Mix" },
  { id: "jerky", name: "Jerky" },
  { id: "popcorn", name: "Popcorn" },
  { id: "energy", name: "Energy" },
];
